pipeline:
        install:
                image: node
                commands:
                        - node -v
                        - npm -v
                        - npm install
                        - npm run test
