version: 2
jobs:
  build:
    working_directory: ~/test
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: setup
          command: 'npm install'
      - run:
          name: test
          command: 'npm run test'
